from PyQt6 import QtCore, QtGui, QtWidgets


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_init(object):
    def setupUi(self, MainWindow_init):
        MainWindow_init.setObjectName("MainWindow_init")
        MainWindow_init.resize(309, 425)
        MainWindow_init.setFixedSize(309, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow_init)
        self.centralwidget.setObjectName("centralwidget")
        self.label_calk_enemy = QtWidgets.QLabel(self.centralwidget)
        self.label_calk_enemy.setGeometry(QtCore.QRect(10, 10, 160, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_calk_enemy.setFont(font)
        self.label_calk_enemy.setStyleSheet("font-weight:bold")
        self.label_calk_enemy.setText("")
        self.label_calk_enemy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_calk_enemy.setObjectName("label_calk_enemy")
        self.pushButton_initiative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initiative.setGeometry(QtCore.QRect(30, 350, 120, 25))
        self.pushButton_initiative.setObjectName("pushButton_initiative")
        self.enemy_name = QtWidgets.QLabel(self.centralwidget)
        self.enemy_name.setGeometry(QtCore.QRect(180, 10, 120, 25))
        self.enemy_name.setStyleSheet("font-weight:bold")
        self.enemy_name.setObjectName("enemy_name")
        self.enemy_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.enemy_name_edit.setGeometry(QtCore.QRect(180, 40, 120, 25))
        self.enemy_name_edit.setObjectName("enemy_name_edit")
        self.enemy_initiative = QtWidgets.QLabel(self.centralwidget)
        self.enemy_initiative.setGeometry(QtCore.QRect(180, 80, 120, 25))
        self.enemy_initiative.setStyleSheet("font-weight:bold")
        self.enemy_initiative.setObjectName("enemy_initiative")
        self.enemy_initiative_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.enemy_initiative_edit.setGeometry(QtCore.QRect(180, 110, 120, 25))
        self.enemy_initiative_edit.setObjectName("enemy_initiative_edit")
        self.label_enemy = QtWidgets.QLabel(self.centralwidget)
        self.label_enemy.setGeometry(QtCore.QRect(180, 180, 121, 171))
        self.label_enemy.setText("")
        self.label_enemy.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_enemy.setObjectName("label_enemy")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(220, 140, 41, 28))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_clean_enemy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean_enemy.setGeometry(QtCore.QRect(180, 350, 120, 25))
        self.pushButton_clean_enemy.setObjectName("pushButton_clean_enemy")
        self.preset_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.preset_edit.setGeometry(QtCore.QRect(182, 390, 81, 22))
        self.preset_edit.setObjectName("preset_edit")
        self.set_preset = QtWidgets.QPushButton(self.centralwidget)
        self.set_preset.setGeometry(QtCore.QRect(270, 390, 31, 22))
        self.set_preset.setObjectName("set_preset")
        self.comboBox_preset = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_preset.setGeometry(QtCore.QRect(30, 390, 73, 22))
        self.comboBox_preset.setObjectName("comboBox_preset")
        self.load_preset = QtWidgets.QPushButton(self.centralwidget)
        self.load_preset.setGeometry(QtCore.QRect(110, 390, 41, 22))
        self.load_preset.setObjectName("load_preset")
        self.del_preset = QtWidgets.QPushButton(self.centralwidget)
        self.del_preset.setGeometry(QtCore.QRect(150, 390, 31, 22))
        self.del_preset.setObjectName("set_preset_2")
        MainWindow_init.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_init)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_init)

    def retranslateUi(self, MainWindow_init):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_init.setWindowTitle(_translate("MainWindow_init", "Calculating initiative"))
        self.pushButton_initiative.setText(_translate("MainWindow_init", "Initiative"))
        self.enemy_name.setText(_translate("MainWindow_init", "Name"))
        self.enemy_initiative.setText(_translate("MainWindow_init", "Initiative"))
        self.pushButton_add.setText(_translate("MainWindow_init", "add"))
        self.pushButton_clean_enemy.setText(_translate("MainWindow_init", "Clear"))
        self.set_preset.setText(_translate("MainWindow_init", "set"))
        self.load_preset.setText(_translate("MainWindow_init", "load"))
        self.del_preset.setText(_translate("MainWindow_init", "del"))


