from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_init(object):
    def setupUi(self, MainWindow_init):
        MainWindow_init.setObjectName("MainWindow_init")
        MainWindow_init.resize(580, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow_init)
        self.centralwidget.setObjectName("centralwidget")
        self.label_calk_enemy = QtWidgets.QLabel(self.centralwidget)
        self.label_calk_enemy.setGeometry(QtCore.QRect(190, 10, 250, 371))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_calk_enemy.setFont(font)
        self.label_calk_enemy.setStyleSheet("font-weight:bold")
        self.label_calk_enemy.setText("")
        self.label_calk_enemy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_calk_enemy.setObjectName("label_calk_enemy")
        self.pushButton_initiative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initiative.setGeometry(QtCore.QRect(255, 390, 120, 25))
        self.pushButton_initiative.setObjectName("pushButton_initiative")
        self.enemy_name = QtWidgets.QLabel(self.centralwidget)
        self.enemy_name.setGeometry(QtCore.QRect(450, 0, 120, 25))
        self.enemy_name.setStyleSheet("font-weight:bold")
        self.enemy_name.setObjectName("enemy_name")
        self.enemy_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.enemy_name_edit.setGeometry(QtCore.QRect(450, 30, 120, 25))
        self.enemy_name_edit.setObjectName("enemy_name_edit")
        self.enemy_initiative = QtWidgets.QLabel(self.centralwidget)
        self.enemy_initiative.setGeometry(QtCore.QRect(450, 60, 120, 25))
        self.enemy_initiative.setStyleSheet("font-weight:bold")
        self.enemy_initiative.setObjectName("enemy_initiative")
        self.enemy_initiative_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.enemy_initiative_edit.setGeometry(QtCore.QRect(450, 90, 81, 25))
        self.enemy_initiative_edit.setObjectName("enemy_initiative_edit")
        self.label_enemy = QtWidgets.QLabel(self.centralwidget)
        self.label_enemy.setGeometry(QtCore.QRect(450, 120, 121, 141))
        self.label_enemy.setText("")
        self.label_enemy.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_enemy.setObjectName("label_enemy")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(530, 90, 41, 25))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_clean_enemy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean_enemy.setGeometry(QtCore.QRect(450, 270, 120, 25))
        self.pushButton_clean_enemy.setObjectName("pushButton_clean_enemy")
        self.preset_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.preset_edit.setGeometry(QtCore.QRect(450, 330, 81, 25))
        self.preset_edit.setObjectName("preset_edit")
        self.set_preset = QtWidgets.QPushButton(self.centralwidget)
        self.set_preset.setGeometry(QtCore.QRect(530, 330, 41, 25))
        self.set_preset.setObjectName("set_preset")
        self.comboBox_preset = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_preset.setGeometry(QtCore.QRect(450, 390, 73, 22))
        self.comboBox_preset.setObjectName("comboBox_preset")
        self.load_preset = QtWidgets.QPushButton(self.centralwidget)
        self.load_preset.setGeometry(QtCore.QRect(530, 390, 41, 22))
        self.load_preset.setObjectName("load_preset")
        self.del_preset = QtWidgets.QPushButton(self.centralwidget)
        self.del_preset.setGeometry(QtCore.QRect(540, 370, 31, 22))
        self.del_preset.setObjectName("del_preset")
        self.box_select_character = QtWidgets.QComboBox(self.centralwidget)
        self.box_select_character.setGeometry(QtCore.QRect(20, 10, 151, 22))
        self.box_select_character.setObjectName("box_select_character")
        self.edit_name_redaction = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name_redaction.setGeometry(QtCore.QRect(20, 60, 115, 25))
        self.edit_name_redaction.setObjectName("edit_name_redaction")
        self.label_enemy_name_redaction = QtWidgets.QLabel(self.centralwidget)
        self.label_enemy_name_redaction.setGeometry(QtCore.QRect(20, 30, 115, 25))
        self.label_enemy_name_redaction.setStyleSheet("font-weight:bold")
        self.label_enemy_name_redaction.setObjectName("label_enemy_name_redaction")
        self.label_enemy_initiative_redaction = QtWidgets.QLabel(self.centralwidget)
        self.label_enemy_initiative_redaction.setGeometry(QtCore.QRect(20, 90, 115, 25))
        self.label_enemy_initiative_redaction.setStyleSheet("font-weight:bold")
        self.label_enemy_initiative_redaction.setObjectName("label_enemy_initiative_redaction")
        self.edit_initiative_redaction = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_initiative_redaction.setGeometry(QtCore.QRect(20, 120, 115, 25))
        self.edit_initiative_redaction.setObjectName("edit_initiative_redaction")
        self.pushButton_set_redaction = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_redaction.setGeometry(QtCore.QRect(20, 150, 93, 28))
        self.pushButton_set_redaction.setObjectName("pushButton_set_redaction")
        self.load_preset_2 = QtWidgets.QLabel(self.centralwidget)
        self.load_preset_2.setGeometry(QtCore.QRect(450, 360, 81, 25))
        self.load_preset_2.setStyleSheet("font-weight:bold")
        self.load_preset_2.setObjectName("load_preset_2")
        self.label_delete_character = QtWidgets.QLabel(self.centralwidget)
        self.label_delete_character.setGeometry(QtCore.QRect(20, 190, 120, 25))
        self.label_delete_character.setStyleSheet("font-weight:bold")
        self.label_delete_character.setObjectName("label_delete_character")
        self.comboBox_del_char = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_del_char.setGeometry(QtCore.QRect(20, 220, 111, 22))
        self.comboBox_del_char.setObjectName("comboBox_del_char")
        self.del_character = QtWidgets.QPushButton(self.centralwidget)
        self.del_character.setGeometry(QtCore.QRect(140, 220, 31, 22))
        self.del_character.setObjectName("del_character")
        self.label_set_player_dice_char_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_set_player_dice_char_0.setGeometry(QtCore.QRect(20, 270, 81, 25))
        self.label_set_player_dice_char_0.setStyleSheet("font-weight:bold")
        self.label_set_player_dice_char_0.setObjectName("label_set_player_dice_char_0")
        self.set_player_dice_edit_char_0 = QtWidgets.QLineEdit(self.centralwidget)
        self.set_player_dice_edit_char_0.setGeometry(QtCore.QRect(110, 270, 51, 25))
        self.set_player_dice_edit_char_0.setObjectName("set_player_dice_edit_char_0")
        self.set_player_dice_edit_char_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.set_player_dice_edit_char_1.setGeometry(QtCore.QRect(110, 300, 51, 25))
        self.set_player_dice_edit_char_1.setObjectName("set_player_dice_edit_char_1")
        self.label_set_player_dice_char_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_set_player_dice_char_1.setGeometry(QtCore.QRect(20, 300, 81, 25))
        self.label_set_player_dice_char_1.setStyleSheet("font-weight:bold")
        self.label_set_player_dice_char_1.setObjectName("label_set_player_dice_char_1")
        self.set_player_dice_edit_char_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.set_player_dice_edit_char_2.setGeometry(QtCore.QRect(110, 330, 51, 25))
        self.set_player_dice_edit_char_2.setObjectName("set_player_dice_edit_char_2")
        self.label_set_player_dice_char_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_set_player_dice_char_2.setGeometry(QtCore.QRect(20, 330, 81, 25))
        self.label_set_player_dice_char_2.setStyleSheet("font-weight:bold")
        self.label_set_player_dice_char_2.setObjectName("label_set_player_dice_char_2")
        self.set_player_dice_edit_char_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.set_player_dice_edit_char_3.setGeometry(QtCore.QRect(110, 360, 51, 25))
        self.set_player_dice_edit_char_3.setObjectName("set_player_dice_edit_char_3")
        self.label_set_player_dice_char_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_set_player_dice_char_3.setGeometry(QtCore.QRect(20, 360, 81, 25))
        self.label_set_player_dice_char_3.setStyleSheet("font-weight:bold")
        self.label_set_player_dice_char_3.setObjectName("label_set_player_dice_char_3")
        self.pushButton_apply_player_dice = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apply_player_dice.setGeometry(QtCore.QRect(50, 390, 93, 28))
        self.pushButton_apply_player_dice.setObjectName("pushButton_apply_player_dice")
        self.load_preset_3 = QtWidgets.QLabel(self.centralwidget)
        self.load_preset_3.setGeometry(QtCore.QRect(450, 300, 81, 25))
        self.load_preset_3.setStyleSheet("font-weight:bold")
        self.load_preset_3.setObjectName("load_preset_3")
        MainWindow_init.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_init)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_init)

    def retranslateUi(self, MainWindow_init):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_init.setWindowTitle(_translate("MainWindow_init", "Calculating initiative"))
        self.pushButton_initiative.setText(_translate("MainWindow_init", "Initiative"))
        self.enemy_name.setText(_translate("MainWindow_init", "Name"))
        self.enemy_initiative.setText(_translate("MainWindow_init", "Initiative"))
        self.pushButton_add.setText(_translate("MainWindow_init", "add"))
        self.pushButton_clean_enemy.setText(_translate("MainWindow_init", "Clear"))
        self.set_preset.setText(_translate("MainWindow_init", "set"))
        self.load_preset.setText(_translate("MainWindow_init", "load"))
        self.del_preset.setText(_translate("MainWindow_init", "del"))
        self.label_enemy_name_redaction.setText(_translate("MainWindow_init", "Name"))
        self.label_enemy_initiative_redaction.setText(_translate("MainWindow_init", "Initiative"))
        self.pushButton_set_redaction.setText(_translate("MainWindow_init", "redaction"))
        self.load_preset_2.setText(_translate("MainWindow_init", "Load preset"))
        self.label_delete_character.setText(_translate("MainWindow_init", "Delete enemy"))
        self.del_character.setText(_translate("MainWindow_init", "del"))
        self.label_set_player_dice_char_0.setText(_translate("MainWindow_init", "Character 1"))
        self.label_set_player_dice_char_1.setText(_translate("MainWindow_init", "Character 2"))
        self.label_set_player_dice_char_2.setText(_translate("MainWindow_init", "Character 3"))
        self.label_set_player_dice_char_3.setText(_translate("MainWindow_init", "Character 4"))
        self.pushButton_apply_player_dice.setText(_translate("MainWindow_init", "Refresh"))
        self.load_preset_3.setText(_translate("MainWindow_init", "Set preset"))







