# Form implementation generated from reading ui file 'initiative_new.redaction_enemy_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_redaction_enemy_in_enemy(object):
    def setupUi(self, Dialog_redaction_enemy_in_enemy):
        Dialog_redaction_enemy_in_enemy.setObjectName("Dialog_redaction_enemy_in_enemy")
        Dialog_redaction_enemy_in_enemy.resize(143, 171)
        self.frame = QtWidgets.QFrame(Dialog_redaction_enemy_in_enemy)
        self.frame.setGeometry(QtCore.QRect(0, 0, 141, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.enemy_name_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_name_edit.setGeometry(QtCore.QRect(0, 30, 120, 25))
        self.enemy_name_edit.setObjectName("enemy_name_edit")
        self.enemy_initiative_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_initiative_edit.setGeometry(QtCore.QRect(0, 80, 61, 25))
        self.enemy_initiative_edit.setObjectName("enemy_initiative_edit")
        self.enemy_hp = QtWidgets.QLabel(self.frame)
        self.enemy_hp.setGeometry(QtCore.QRect(0, 110, 21, 25))
        self.enemy_hp.setStyleSheet("font-weight:bold")
        self.enemy_hp.setObjectName("enemy_hp")
        self.enemy_name = QtWidgets.QLabel(self.frame)
        self.enemy_name.setGeometry(QtCore.QRect(0, 0, 120, 25))
        self.enemy_name.setStyleSheet("font-weight:bold")
        self.enemy_name.setObjectName("enemy_name")
        self.enemy_initiative = QtWidgets.QLabel(self.frame)
        self.enemy_initiative.setGeometry(QtCore.QRect(0, 50, 61, 25))
        self.enemy_initiative.setStyleSheet("font-weight:bold")
        self.enemy_initiative.setObjectName("enemy_initiative")
        self.enemy_hp_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_hp_edit.setGeometry(QtCore.QRect(0, 140, 61, 25))
        self.enemy_hp_edit.setObjectName("enemy_hp_edit")
        self.pushButton_cansel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cansel.setGeometry(QtCore.QRect(90, 140, 31, 23))
        self.pushButton_cansel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cansel.setIcon(icon)
        self.pushButton_cansel.setObjectName("pushButton_cansel")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setGeometry(QtCore.QRect(90, 110, 31, 23))
        self.pushButton_ok.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_ok.setIcon(icon1)
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.pushButton_ok.clicked.connect(Dialog_redaction_enemy_in_enemy.close)
        self.pushButton_cansel.clicked.connect(Dialog_redaction_enemy_in_enemy.close)

        self.retranslateUi(Dialog_redaction_enemy_in_enemy)
        QtCore.QMetaObject.connectSlotsByName(Dialog_redaction_enemy_in_enemy)

    def retranslateUi(self, Dialog_redaction_enemy_in_enemy):
        _translate = QtCore.QCoreApplication.translate
        Dialog_redaction_enemy_in_enemy.setWindowTitle(_translate("Dialog_redaction_enemy_in_enemy", "Dialog"))
        self.enemy_hp.setText(_translate("Dialog_redaction_enemy_in_enemy", "HP"))
        self.enemy_name.setText(_translate("Dialog_redaction_enemy_in_enemy", "Name"))
        self.enemy_initiative.setText(_translate("Dialog_redaction_enemy_in_enemy", "Initiative"))

        # self.pushButton_ok.clicked.connect(Dialog_redaction_enemy_in_enemy.close)
        # self.pushButton_cansel.clicked.connect(Dialog_redaction_enemy_in_enemy.close)
