# Form implementation generated from reading ui file 'initiative_new.add_enemy_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_enemy(object):
    def setupUi(self, Dialog_add_enemy):
        Dialog_add_enemy.setObjectName("Dialog_add_enemy")
        Dialog_add_enemy.resize(131, 191)
        self.frame = QtWidgets.QFrame(Dialog_add_enemy)
        self.frame.setGeometry(QtCore.QRect(0, 0, 131, 191))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(85, 85, 85);\n"
"    opacity: 0.3;\n"
"    color: rgb(247, 147, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(55, 55, 55);\n"
"    color: rgb(247, 147, 30);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(55, 55, 55);\n"
"    border-radius: 5px;\n"
"    color: rgb(247, 147, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(105, 105, 105);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background-color: rgb(55, 55, 55);\n"
"    color: rgb(247, 147, 30);\n"
"    border: none;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.enemy_name = QtWidgets.QLabel(self.frame)
        self.enemy_name.setGeometry(QtCore.QRect(0, 0, 120, 25))
        self.enemy_name.setStyleSheet("font-weight:bold")
        self.enemy_name.setObjectName("enemy_name")
        self.enemy_initiative_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_initiative_edit.setGeometry(QtCore.QRect(0, 100, 51, 25))
        self.enemy_initiative_edit.setObjectName("enemy_initiative_edit")
        self.enemy_hp_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_hp_edit.setGeometry(QtCore.QRect(70, 100, 51, 25))
        self.enemy_hp_edit.setObjectName("enemy_hp_edit")
        self.enemy_initiative = QtWidgets.QLabel(self.frame)
        self.enemy_initiative.setGeometry(QtCore.QRect(0, 70, 61, 25))
        self.enemy_initiative.setStyleSheet("font-weight:bold")
        self.enemy_initiative.setObjectName("enemy_initiative")
        self.enemy_name_edit = QtWidgets.QLineEdit(self.frame)
        self.enemy_name_edit.setGeometry(QtCore.QRect(0, 30, 120, 25))
        self.enemy_name_edit.setObjectName("enemy_name_edit")
        self.enemy_hp = QtWidgets.QLabel(self.frame)
        self.enemy_hp.setGeometry(QtCore.QRect(70, 70, 21, 25))
        self.enemy_hp.setStyleSheet("font-weight:bold")
        self.enemy_hp.setObjectName("enemy_hp")
        self.enemy_amount = QtWidgets.QLabel(self.frame)
        self.enemy_amount.setGeometry(QtCore.QRect(0, 130, 51, 25))
        self.enemy_amount.setStyleSheet("font-weight:bold")
        self.enemy_amount.setObjectName("enemy_amount")
        self.spinBox_amount_enemy = QtWidgets.QSpinBox(self.frame)
        self.spinBox_amount_enemy.setGeometry(QtCore.QRect(0, 160, 42, 22))
        self.spinBox_amount_enemy.setObjectName("spinBox_amount_enemy")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setGeometry(QtCore.QRect(90, 130, 31, 23))
        self.pushButton_ok.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/new_icon/ico/plus.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_ok.setIcon(icon)
        self.pushButton_ok.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cansel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cansel.setGeometry(QtCore.QRect(90, 160, 31, 23))
        self.pushButton_cansel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/new_icon/ico/x.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cansel.setIcon(icon1)
        self.pushButton_cansel.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_cansel.setObjectName("pushButton_cansel")

        self.pushButton_ok.clicked.connect(Dialog_add_enemy.close)
        self.pushButton_cansel.clicked.connect(Dialog_add_enemy.close)

        self.retranslateUi(Dialog_add_enemy)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add_enemy)

    def retranslateUi(self, Dialog_add_enemy):
        _translate = QtCore.QCoreApplication.translate
        Dialog_add_enemy.setWindowTitle(_translate("Dialog_add_enemy", "Dialog"))
        self.enemy_name.setText(_translate("Dialog_add_enemy", "Name"))
        self.enemy_initiative.setText(_translate("Dialog_add_enemy", "Initiative"))
        self.enemy_hp.setText(_translate("Dialog_add_enemy", "HP"))
        self.enemy_amount.setText(_translate("Dialog_add_enemy", "Amount"))
