from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 425)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 399))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.hp = QtWidgets.QLabel(self.tab)
        self.hp.setGeometry(QtCore.QRect(0, 80, 31, 25))
        self.hp.setStyleSheet("font-weight:bold")
        self.hp.setObjectName("hp")
        self.initiative_edit = QtWidgets.QLineEdit(self.tab)
        self.initiative_edit.setGeometry(QtCore.QRect(0, 285, 120, 25))
        self.initiative_edit.setObjectName("initiative_edit")
        self.hp_edit = QtWidgets.QLineEdit(self.tab)
        self.hp_edit.setGeometry(QtCore.QRect(0, 105, 41, 25))
        self.hp_edit.setObjectName("hp_edit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(0, 315, 120, 25))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(130, 10, 151, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight:bold")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLabel(self.tab)
        self.name.setGeometry(QtCore.QRect(0, 25, 120, 25))
        self.name.setStyleSheet("font-weight:bold")
        self.name.setObjectName("name")
        self.name_edit = QtWidgets.QLineEdit(self.tab)
        self.name_edit.setGeometry(QtCore.QRect(0, 50, 120, 25))
        self.name_edit.setObjectName("name_edit")
        self.initiative = QtWidgets.QLabel(self.tab)
        self.initiative.setGeometry(QtCore.QRect(0, 260, 120, 25))
        self.initiative.setStyleSheet("font-weight:bold")
        self.initiative.setObjectName("initiative")
        self.label_roll_dice = QtWidgets.QLabel(self.tab)
        self.label_roll_dice.setGeometry(QtCore.QRect(0, 50, 120, 20))
        self.label_roll_dice.setStyleSheet("font-weight:bold")
        self.label_roll_dice.setText("")
        self.label_roll_dice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_roll_dice.setObjectName("label_roll_dice")
        self.pushButton_roll_dice = QtWidgets.QPushButton(self.tab)
        self.pushButton_roll_dice.setGeometry(QtCore.QRect(0, 70, 120, 25))
        self.pushButton_roll_dice.setObjectName("pushButton_roll_dice")
        self.amount_dice_box = QtWidgets.QSpinBox(self.tab)
        self.amount_dice_box.setGeometry(QtCore.QRect(40, 100, 41, 22))
        self.amount_dice_box.setMinimum(1)
        self.amount_dice_box.setObjectName("amount_dice_box")
        self.dice_edit = QtWidgets.QLineEdit(self.tab)
        self.dice_edit.setGeometry(QtCore.QRect(40, 120, 41, 22))
        self.dice_edit.setObjectName("dice_edit")
        self.label_amount = QtWidgets.QLabel(self.tab)
        self.label_amount.setGeometry(QtCore.QRect(0, 100, 41, 16))
        self.label_amount.setObjectName("label_amount")
        self.radioButton_hide_create = QtWidgets.QRadioButton(self.tab)
        self.radioButton_hide_create.setGeometry(QtCore.QRect(10, 340, 115, 20))
        self.radioButton_hide_create.setChecked(False)
        self.radioButton_hide_create.setAutoRepeat(False)
        self.radioButton_hide_create.setObjectName("radioButton_hide_create")
        self.name_character0 = QtWidgets.QLabel(self.tab)
        self.name_character0.setGeometry(QtCore.QRect(150, 20, 120, 25))
        self.name_character0.setStyleSheet("font-weight:bold")
        self.name_character0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_character0.setObjectName("name_character0")
        self.hp_edit_character0 = QtWidgets.QLineEdit(self.tab)
        self.hp_edit_character0.setGeometry(QtCore.QRect(179, 50, 31, 25))
        self.hp_edit_character0.setText("")
        self.hp_edit_character0.setObjectName("hp_edit_character0")
        self.hp_character0 = QtWidgets.QLabel(self.tab)
        self.hp_character0.setGeometry(QtCore.QRect(150, 50, 25, 25))
        self.hp_character0.setStyleSheet("font-weight:bold")
        self.hp_character0.setObjectName("hp_character0")
        self.initiative_character0 = QtWidgets.QLabel(self.tab)
        self.initiative_character0.setGeometry(QtCore.QRect(160, 260, 61, 25))
        self.initiative_character0.setStyleSheet("font-weight:bold")
        self.initiative_character0.setObjectName("initiative_character0")
        self.initiative_edit_character0 = QtWidgets.QLineEdit(self.tab)
        self.initiative_edit_character0.setGeometry(QtCore.QRect(230, 260, 51, 25))
        self.initiative_edit_character0.setObjectName("initiative_edit_character0")
        self.name_character1 = QtWidgets.QLabel(self.tab)
        self.name_character1.setGeometry(QtCore.QRect(310, 20, 120, 25))
        self.name_character1.setStyleSheet("font-weight:bold")
        self.name_character1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_character1.setObjectName("name_character1")
        self.hp_edit_character1 = QtWidgets.QLineEdit(self.tab)
        self.hp_edit_character1.setGeometry(QtCore.QRect(339, 50, 31, 25))
        self.hp_edit_character1.setObjectName("hp_edit_character1")
        self.initiative_edit_character1 = QtWidgets.QLineEdit(self.tab)
        self.initiative_edit_character1.setGeometry(QtCore.QRect(390, 260, 51, 25))
        self.initiative_edit_character1.setObjectName("initiative_edit_character1")
        self.initiative_character1 = QtWidgets.QLabel(self.tab)
        self.initiative_character1.setGeometry(QtCore.QRect(320, 260, 61, 25))
        self.initiative_character1.setStyleSheet("font-weight:bold")
        self.initiative_character1.setObjectName("initiative_character1")
        self.hp_character1 = QtWidgets.QLabel(self.tab)
        self.hp_character1.setGeometry(QtCore.QRect(310, 50, 25, 25))
        self.hp_character1.setStyleSheet("font-weight:bold")
        self.hp_character1.setObjectName("hp_character1")
        self.name_character2 = QtWidgets.QLabel(self.tab)
        self.name_character2.setGeometry(QtCore.QRect(480, 20, 120, 25))
        self.name_character2.setStyleSheet("font-weight:bold")
        self.name_character2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_character2.setObjectName("name_character2")
        self.initiative_character3 = QtWidgets.QLabel(self.tab)
        self.initiative_character3.setGeometry(QtCore.QRect(640, 260, 61, 25))
        self.initiative_character3.setStyleSheet("font-weight:bold")
        self.initiative_character3.setObjectName("initiative_character3")
        self.hp_edit_character2 = QtWidgets.QLineEdit(self.tab)
        self.hp_edit_character2.setGeometry(QtCore.QRect(509, 50, 31, 25))
        self.hp_edit_character2.setObjectName("hp_edit_character2")
        self.hp_edit_character3 = QtWidgets.QLineEdit(self.tab)
        self.hp_edit_character3.setGeometry(QtCore.QRect(669, 50, 31, 25))
        self.hp_edit_character3.setObjectName("hp_edit_character3")
        self.name_character3 = QtWidgets.QLabel(self.tab)
        self.name_character3.setGeometry(QtCore.QRect(640, 20, 120, 25))
        self.name_character3.setStyleSheet("font-weight:bold")
        self.name_character3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_character3.setObjectName("name_character3")
        self.initiative_edit_character2 = QtWidgets.QLineEdit(self.tab)
        self.initiative_edit_character2.setGeometry(QtCore.QRect(550, 260, 51, 25))
        self.initiative_edit_character2.setObjectName("initiative_edit_character2")
        self.initiative_character2 = QtWidgets.QLabel(self.tab)
        self.initiative_character2.setGeometry(QtCore.QRect(480, 260, 61, 25))
        self.initiative_character2.setStyleSheet("font-weight:bold")
        self.initiative_character2.setObjectName("initiative_character2")
        self.initiative_edit_character3 = QtWidgets.QLineEdit(self.tab)
        self.initiative_edit_character3.setGeometry(QtCore.QRect(710, 260, 51, 25))
        self.initiative_edit_character3.setObjectName("initiative_edit_character3")
        self.hp_character3 = QtWidgets.QLabel(self.tab)
        self.hp_character3.setGeometry(QtCore.QRect(640, 50, 25, 25))
        self.hp_character3.setStyleSheet("font-weight:bold")
        self.hp_character3.setObjectName("hp_character3")
        self.hp_character2 = QtWidgets.QLabel(self.tab)
        self.hp_character2.setGeometry(QtCore.QRect(480, 50, 25, 25))
        self.hp_character2.setStyleSheet("font-weight:bold")
        self.hp_character2.setObjectName("hp_character2")
        self.spell_slot_edit = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit.setGeometry(QtCore.QRect(0, 160, 25, 25))
        self.spell_slot_edit.setObjectName("spell_slot_edit")
        self.spell_slot_edit_2 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_2.setGeometry(QtCore.QRect(30, 160, 25, 25))
        self.spell_slot_edit_2.setObjectName("spell_slot_edit_2")
        self.spell_slot_edit_3 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_3.setGeometry(QtCore.QRect(60, 160, 25, 25))
        self.spell_slot_edit_3.setObjectName("spell_slot_edit_3")
        self.spell_slot_edit_4 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_4.setGeometry(QtCore.QRect(90, 160, 25, 25))
        self.spell_slot_edit_4.setObjectName("spell_slot_edit_4")
        self.spell_slot_edit_5 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_5.setGeometry(QtCore.QRect(120, 160, 25, 25))
        self.spell_slot_edit_5.setObjectName("spell_slot_edit_5")
        self.spell_slot_edit_6 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_6.setGeometry(QtCore.QRect(0, 210, 25, 25))
        self.spell_slot_edit_6.setObjectName("spell_slot_edit_6")
        self.spell_slot_edit_7 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_7.setGeometry(QtCore.QRect(30, 210, 25, 25))
        self.spell_slot_edit_7.setObjectName("spell_slot_edit_7")
        self.spell_slot_edit_8 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_8.setGeometry(QtCore.QRect(60, 210, 25, 25))
        self.spell_slot_edit_8.setObjectName("spell_slot_edit_8")
        self.spell_slot_edit_9 = QtWidgets.QLineEdit(self.tab)
        self.spell_slot_edit_9.setGeometry(QtCore.QRect(90, 210, 25, 25))
        self.spell_slot_edit_9.setObjectName("spell_slot_edit_9")
        self.spell_slot = QtWidgets.QLabel(self.tab)
        self.spell_slot.setGeometry(QtCore.QRect(0, 140, 120, 25))
        self.spell_slot.setStyleSheet("font-weight:bold")
        self.spell_slot.setObjectName("spell_slot")
        self.label_spell_slot = QtWidgets.QLabel(self.tab)
        self.label_spell_slot.setGeometry(QtCore.QRect(0, 190, 20, 20))
        self.label_spell_slot.setStyleSheet("font-weight:bold")
        self.label_spell_slot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot.setObjectName("label_spell_slot")
        self.label_spell_slot_2 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_2.setGeometry(QtCore.QRect(30, 190, 20, 20))
        self.label_spell_slot_2.setStyleSheet("font-weight:bold")
        self.label_spell_slot_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_2.setObjectName("label_spell_slot_2")
        self.label_spell_slot_3 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_3.setGeometry(QtCore.QRect(60, 190, 20, 20))
        self.label_spell_slot_3.setStyleSheet("font-weight:bold")
        self.label_spell_slot_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_3.setObjectName("label_spell_slot_3")
        self.label_spell_slot_4 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_4.setGeometry(QtCore.QRect(90, 190, 20, 20))
        self.label_spell_slot_4.setStyleSheet("font-weight:bold")
        self.label_spell_slot_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_4.setObjectName("label_spell_slot_4")
        self.label_spell_slot_5 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_5.setGeometry(QtCore.QRect(120, 190, 20, 20))
        self.label_spell_slot_5.setStyleSheet("font-weight:bold")
        self.label_spell_slot_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_5.setObjectName("label_spell_slot_5")
        self.label_spell_slot_6 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_6.setGeometry(QtCore.QRect(0, 240, 20, 20))
        self.label_spell_slot_6.setStyleSheet("font-weight:bold")
        self.label_spell_slot_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_6.setObjectName("label_spell_slot_6")
        self.label_spell_slot_7 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_7.setGeometry(QtCore.QRect(30, 240, 20, 20))
        self.label_spell_slot_7.setStyleSheet("font-weight:bold")
        self.label_spell_slot_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_7.setObjectName("label_spell_slot_7")
        self.label_spell_slot_8 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_8.setGeometry(QtCore.QRect(60, 240, 20, 20))
        self.label_spell_slot_8.setStyleSheet("font-weight:bold")
        self.label_spell_slot_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_8.setObjectName("label_spell_slot_8")
        self.label_spell_slot_9 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_9.setGeometry(QtCore.QRect(90, 240, 20, 20))
        self.label_spell_slot_9.setStyleSheet("font-weight:bold")
        self.label_spell_slot_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_9.setObjectName("label_spell_slot_9")
        self.spin_spell_slot_character0 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0.setGeometry(QtCore.QRect(150, 110, 42, 22))
        self.spin_spell_slot_character0.setObjectName("spin_spell_slot_character0")
        self.spin_spell_slot_character0_2 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_2.setGeometry(QtCore.QRect(200, 110, 42, 22))
        self.spin_spell_slot_character0_2.setObjectName("spin_spell_slot_character0_2")
        self.spin_spell_slot_character0_3 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_3.setGeometry(QtCore.QRect(250, 110, 42, 22))
        self.spin_spell_slot_character0_3.setObjectName("spin_spell_slot_character0_3")
        self.spin_spell_slot_character0_4 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_4.setGeometry(QtCore.QRect(150, 150, 42, 22))
        self.spin_spell_slot_character0_4.setObjectName("spin_spell_slot_character0_4")
        self.spin_spell_slot_character0_5 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_5.setGeometry(QtCore.QRect(200, 150, 42, 22))
        self.spin_spell_slot_character0_5.setObjectName("spin_spell_slot_character0_5")
        self.spin_spell_slot_character0_6 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_6.setGeometry(QtCore.QRect(250, 150, 42, 22))
        self.spin_spell_slot_character0_6.setObjectName("spin_spell_slot_character0_6")
        self.spin_spell_slot_character0_7 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_7.setGeometry(QtCore.QRect(150, 190, 42, 22))
        self.spin_spell_slot_character0_7.setObjectName("spin_spell_slot_character0_7")
        self.spin_spell_slot_character0_8 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_8.setGeometry(QtCore.QRect(200, 190, 42, 22))
        self.spin_spell_slot_character0_8.setObjectName("spin_spell_slot_character0_8")
        self.spin_spell_slot_character0_9 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character0_9.setGeometry(QtCore.QRect(250, 190, 42, 22))
        self.spin_spell_slot_character0_9.setObjectName("spin_spell_slot_character0_9")
        self.label_spell_slot_character0 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0.setGeometry(QtCore.QRect(160, 130, 20, 20))
        self.label_spell_slot_character0.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0.setObjectName("label_spell_slot_character0")
        self.label_spell_slot_character0_2 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_2.setGeometry(QtCore.QRect(210, 130, 20, 20))
        self.label_spell_slot_character0_2.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_2.setObjectName("label_spell_slot_character0_2")
        self.label_spell_slot_character0_3 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_3.setGeometry(QtCore.QRect(260, 130, 20, 20))
        self.label_spell_slot_character0_3.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_3.setObjectName("label_spell_slot_character0_3")
        self.label_spell_slot_character0_4 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_4.setGeometry(QtCore.QRect(160, 170, 20, 20))
        self.label_spell_slot_character0_4.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_4.setObjectName("label_spell_slot_character0_4")
        self.label_spell_slot_character0_5 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_5.setGeometry(QtCore.QRect(210, 170, 20, 20))
        self.label_spell_slot_character0_5.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_5.setObjectName("label_spell_slot_character0_5")
        self.label_spell_slot_character0_6 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_6.setGeometry(QtCore.QRect(260, 170, 20, 20))
        self.label_spell_slot_character0_6.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_6.setObjectName("label_spell_slot_character0_6")
        self.label_spell_slot_character0_7 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_7.setGeometry(QtCore.QRect(160, 210, 20, 20))
        self.label_spell_slot_character0_7.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_7.setObjectName("label_spell_slot_character0_7")
        self.label_spell_slot_character0_8 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_8.setGeometry(QtCore.QRect(210, 210, 20, 20))
        self.label_spell_slot_character0_8.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_8.setObjectName("label_spell_slot_character0_8")
        self.label_spell_slot_character0_9 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_9.setGeometry(QtCore.QRect(260, 210, 20, 20))
        self.label_spell_slot_character0_9.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_9.setObjectName("label_spell_slot_character0_9")
        self.spell_slot_label_traker_char0 = QtWidgets.QLabel(self.tab)
        self.spell_slot_label_traker_char0.setGeometry(QtCore.QRect(150, 80, 61, 25))
        self.spell_slot_label_traker_char0.setStyleSheet("font-weight:bold")
        self.spell_slot_label_traker_char0.setObjectName("spell_slot_label_traker_char0")
        self.spin_spell_slot_character1_4 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_4.setGeometry(QtCore.QRect(310, 150, 42, 22))
        self.spin_spell_slot_character1_4.setObjectName("spin_spell_slot_character1_4")
        self.label_spell_slot_character0_10 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_10.setGeometry(QtCore.QRect(420, 210, 20, 20))
        self.label_spell_slot_character0_10.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_10.setObjectName("label_spell_slot_character0_10")
        self.spell_slot_label_traker_char1 = QtWidgets.QLabel(self.tab)
        self.spell_slot_label_traker_char1.setGeometry(QtCore.QRect(310, 80, 61, 25))
        self.spell_slot_label_traker_char1.setStyleSheet("font-weight:bold")
        self.spell_slot_label_traker_char1.setObjectName("spell_slot_label_traker_char1")
        self.label_spell_slot_character0_11 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_11.setGeometry(QtCore.QRect(370, 210, 20, 20))
        self.label_spell_slot_character0_11.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_11.setObjectName("label_spell_slot_character0_11")
        self.spin_spell_slot_character1_3 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_3.setGeometry(QtCore.QRect(410, 110, 42, 22))
        self.spin_spell_slot_character1_3.setObjectName("spin_spell_slot_character1_3")
        self.label_spell_slot_character0_12 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_12.setGeometry(QtCore.QRect(320, 210, 20, 20))
        self.label_spell_slot_character0_12.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_12.setObjectName("label_spell_slot_character0_12")
        self.spin_spell_slot_character1 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1.setGeometry(QtCore.QRect(310, 110, 42, 22))
        self.spin_spell_slot_character1.setObjectName("spin_spell_slot_character1")
        self.spin_spell_slot_character1_8 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_8.setGeometry(QtCore.QRect(360, 190, 42, 22))
        self.spin_spell_slot_character1_8.setObjectName("spin_spell_slot_character1_8")
        self.label_spell_slot_character0_13 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_13.setGeometry(QtCore.QRect(370, 130, 20, 20))
        self.label_spell_slot_character0_13.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_13.setObjectName("label_spell_slot_character0_13")
        self.label_spell_slot_character0_14 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_14.setGeometry(QtCore.QRect(320, 170, 20, 20))
        self.label_spell_slot_character0_14.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_14.setObjectName("label_spell_slot_character0_14")
        self.label_spell_slot_character0_15 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_15.setGeometry(QtCore.QRect(320, 130, 20, 20))
        self.label_spell_slot_character0_15.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_15.setObjectName("label_spell_slot_character0_15")
        self.spin_spell_slot_character1_6 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_6.setGeometry(QtCore.QRect(410, 150, 42, 22))
        self.spin_spell_slot_character1_6.setObjectName("spin_spell_slot_character1_6")
        self.spin_spell_slot_character1_9 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_9.setGeometry(QtCore.QRect(410, 190, 42, 22))
        self.spin_spell_slot_character1_9.setObjectName("spin_spell_slot_character1_9")
        self.label_spell_slot_character0_16 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_16.setGeometry(QtCore.QRect(370, 170, 20, 20))
        self.label_spell_slot_character0_16.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_16.setObjectName("label_spell_slot_character0_16")
        self.spin_spell_slot_character1_5 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_5.setGeometry(QtCore.QRect(360, 150, 42, 22))
        self.spin_spell_slot_character1_5.setObjectName("spin_spell_slot_character1_5")
        self.spin_spell_slot_character1_7 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_7.setGeometry(QtCore.QRect(310, 190, 42, 22))
        self.spin_spell_slot_character1_7.setObjectName("spin_spell_slot_character1_7")
        self.label_spell_slot_character0_17 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_17.setGeometry(QtCore.QRect(420, 130, 20, 20))
        self.label_spell_slot_character0_17.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_17.setObjectName("label_spell_slot_character0_17")
        self.spin_spell_slot_character1_2 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character1_2.setGeometry(QtCore.QRect(360, 110, 42, 22))
        self.spin_spell_slot_character1_2.setObjectName("spin_spell_slot_character1_2")
        self.label_spell_slot_character0_18 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_18.setGeometry(QtCore.QRect(420, 170, 20, 20))
        self.label_spell_slot_character0_18.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_18.setObjectName("label_spell_slot_character0_18")
        self.label_spell_slot_character0_19 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_19.setGeometry(QtCore.QRect(490, 170, 20, 20))
        self.label_spell_slot_character0_19.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_19.setObjectName("label_spell_slot_character0_19")
        self.label_spell_slot_character0_20 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_20.setGeometry(QtCore.QRect(490, 210, 20, 20))
        self.label_spell_slot_character0_20.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_20.setObjectName("label_spell_slot_character0_20")
        self.spin_spell_slot_character2_4 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_4.setGeometry(QtCore.QRect(480, 150, 42, 22))
        self.spin_spell_slot_character2_4.setObjectName("spin_spell_slot_character2_4")
        self.label_spell_slot_character0_21 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_21.setGeometry(QtCore.QRect(540, 130, 20, 20))
        self.label_spell_slot_character0_21.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_21.setObjectName("label_spell_slot_character0_21")
        self.spin_spell_slot_character2 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2.setGeometry(QtCore.QRect(480, 110, 42, 22))
        self.spin_spell_slot_character2.setObjectName("spin_spell_slot_character2")
        self.spin_spell_slot_character2_2 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_2.setGeometry(QtCore.QRect(530, 110, 42, 22))
        self.spin_spell_slot_character2_2.setObjectName("spin_spell_slot_character2_2")
        self.spin_spell_slot_character2_5 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_5.setGeometry(QtCore.QRect(530, 150, 42, 22))
        self.spin_spell_slot_character2_5.setObjectName("spin_spell_slot_character2_5")
        self.spell_slot_label_traker_char2 = QtWidgets.QLabel(self.tab)
        self.spell_slot_label_traker_char2.setGeometry(QtCore.QRect(480, 80, 61, 25))
        self.spell_slot_label_traker_char2.setStyleSheet("font-weight:bold")
        self.spell_slot_label_traker_char2.setObjectName("spell_slot_label_traker_char2")
        self.label_spell_slot_character0_22 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_22.setGeometry(QtCore.QRect(540, 210, 20, 20))
        self.label_spell_slot_character0_22.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_22.setObjectName("label_spell_slot_character0_22")
        self.label_spell_slot_character0_23 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_23.setGeometry(QtCore.QRect(590, 170, 20, 20))
        self.label_spell_slot_character0_23.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_23.setObjectName("label_spell_slot_character0_23")
        self.spin_spell_slot_character2_3 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_3.setGeometry(QtCore.QRect(580, 110, 42, 22))
        self.spin_spell_slot_character2_3.setObjectName("spin_spell_slot_character2_3")
        self.spin_spell_slot_character2_6 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_6.setGeometry(QtCore.QRect(580, 150, 42, 22))
        self.spin_spell_slot_character2_6.setObjectName("spin_spell_slot_character2_6")
        self.label_spell_slot_character0_24 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_24.setGeometry(QtCore.QRect(490, 130, 20, 20))
        self.label_spell_slot_character0_24.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_24.setObjectName("label_spell_slot_character0_24")
        self.spin_spell_slot_character2_7 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_7.setGeometry(QtCore.QRect(480, 190, 42, 22))
        self.spin_spell_slot_character2_7.setObjectName("spin_spell_slot_character2_7")
        self.label_spell_slot_character0_25 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_25.setGeometry(QtCore.QRect(540, 170, 20, 20))
        self.label_spell_slot_character0_25.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_25.setObjectName("label_spell_slot_character0_25")
        self.spin_spell_slot_character2_8 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_8.setGeometry(QtCore.QRect(530, 190, 42, 22))
        self.spin_spell_slot_character2_8.setObjectName("spin_spell_slot_character2_8")
        self.label_spell_slot_character0_26 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_26.setGeometry(QtCore.QRect(590, 130, 20, 20))
        self.label_spell_slot_character0_26.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_26.setObjectName("label_spell_slot_character0_26")
        self.spin_spell_slot_character2_9 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character2_9.setGeometry(QtCore.QRect(580, 190, 42, 22))
        self.spin_spell_slot_character2_9.setObjectName("spin_spell_slot_character2_9")
        self.label_spell_slot_character0_27 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_27.setGeometry(QtCore.QRect(590, 210, 20, 20))
        self.label_spell_slot_character0_27.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_27.setObjectName("label_spell_slot_character0_27")
        self.label_spell_slot_character0_28 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_28.setGeometry(QtCore.QRect(650, 170, 20, 20))
        self.label_spell_slot_character0_28.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_28.setObjectName("label_spell_slot_character0_28")
        self.label_spell_slot_character0_29 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_29.setGeometry(QtCore.QRect(650, 210, 20, 20))
        self.label_spell_slot_character0_29.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_29.setObjectName("label_spell_slot_character0_29")
        self.spin_spell_slot_character3_4 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_4.setGeometry(QtCore.QRect(640, 150, 42, 22))
        self.spin_spell_slot_character3_4.setObjectName("spin_spell_slot_character3_4")
        self.label_spell_slot_character0_30 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_30.setGeometry(QtCore.QRect(700, 130, 20, 20))
        self.label_spell_slot_character0_30.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_30.setObjectName("label_spell_slot_character0_30")
        self.spin_spell_slot_character3 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3.setGeometry(QtCore.QRect(640, 110, 42, 22))
        self.spin_spell_slot_character3.setObjectName("spin_spell_slot_character3")
        self.spin_spell_slot_character3_2 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_2.setGeometry(QtCore.QRect(690, 110, 42, 22))
        self.spin_spell_slot_character3_2.setObjectName("spin_spell_slot_character3_2")
        self.spin_spell_slot_character3_5 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_5.setGeometry(QtCore.QRect(690, 150, 42, 22))
        self.spin_spell_slot_character3_5.setObjectName("spin_spell_slot_character3_5")
        self.spell_slot_label_traker_char3 = QtWidgets.QLabel(self.tab)
        self.spell_slot_label_traker_char3.setGeometry(QtCore.QRect(640, 80, 61, 25))
        self.spell_slot_label_traker_char3.setStyleSheet("font-weight:bold")
        self.spell_slot_label_traker_char3.setObjectName("spell_slot_label_traker_char3")
        self.label_spell_slot_character0_31 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_31.setGeometry(QtCore.QRect(700, 210, 20, 20))
        self.label_spell_slot_character0_31.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_31.setObjectName("label_spell_slot_character0_31")
        self.label_spell_slot_character0_32 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_32.setGeometry(QtCore.QRect(750, 170, 20, 20))
        self.label_spell_slot_character0_32.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_32.setObjectName("label_spell_slot_character0_32")
        self.spin_spell_slot_character3_3 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_3.setGeometry(QtCore.QRect(740, 110, 42, 22))
        self.spin_spell_slot_character3_3.setObjectName("spin_spell_slot_character3_3")
        self.spin_spell_slot_character3_6 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_6.setGeometry(QtCore.QRect(740, 150, 42, 22))
        self.spin_spell_slot_character3_6.setObjectName("spin_spell_slot_character3_6")
        self.label_spell_slot_character0_33 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_33.setGeometry(QtCore.QRect(650, 130, 20, 20))
        self.label_spell_slot_character0_33.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_33.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_33.setObjectName("label_spell_slot_character0_33")
        self.spin_spell_slot_character3_7 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_7.setGeometry(QtCore.QRect(640, 190, 42, 22))
        self.spin_spell_slot_character3_7.setObjectName("spin_spell_slot_character3_7")
        self.label_spell_slot_character0_34 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_34.setGeometry(QtCore.QRect(700, 170, 20, 20))
        self.label_spell_slot_character0_34.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_34.setObjectName("label_spell_slot_character0_34")
        self.spin_spell_slot_character3_8 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_8.setGeometry(QtCore.QRect(690, 190, 42, 22))
        self.spin_spell_slot_character3_8.setObjectName("spin_spell_slot_character3_8")
        self.label_spell_slot_character0_35 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_35.setGeometry(QtCore.QRect(750, 130, 20, 20))
        self.label_spell_slot_character0_35.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_35.setObjectName("label_spell_slot_character0_35")
        self.spin_spell_slot_character3_9 = QtWidgets.QSpinBox(self.tab)
        self.spin_spell_slot_character3_9.setGeometry(QtCore.QRect(740, 190, 42, 22))
        self.spin_spell_slot_character3_9.setObjectName("spin_spell_slot_character3_9")
        self.label_spell_slot_character0_36 = QtWidgets.QLabel(self.tab)
        self.label_spell_slot_character0_36.setGeometry(QtCore.QRect(750, 210, 20, 20))
        self.label_spell_slot_character0_36.setStyleSheet("font-weight:bold")
        self.label_spell_slot_character0_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spell_slot_character0_36.setObjectName("label_spell_slot_character0_36")
        self.pushButton_restore_spell_slots_0 = QtWidgets.QPushButton(self.tab)
        self.pushButton_restore_spell_slots_0.setGeometry(QtCore.QRect(150, 230, 93, 28))
        self.pushButton_restore_spell_slots_0.setObjectName("pushButton_restore_spell_slots_0")
        self.pushButton_restore_spell_slots_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_restore_spell_slots_1.setGeometry(QtCore.QRect(310, 230, 93, 28))
        self.pushButton_restore_spell_slots_1.setObjectName("pushButton_restore_spell_slots_1")
        self.pushButton_restore_spell_slots_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_restore_spell_slots_2.setGeometry(QtCore.QRect(480, 230, 93, 28))
        self.pushButton_restore_spell_slots_2.setObjectName("pushButton_restore_spell_slots_2")
        self.pushButton_restore_spell_slots_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_restore_spell_slots_3.setGeometry(QtCore.QRect(640, 230, 93, 28))
        self.pushButton_restore_spell_slots_3.setObjectName("pushButton_restore_spell_slots_3")
        self.label_lock_init_char_0 = QtWidgets.QLabel(self.tab)
        self.label_lock_init_char_0.setGeometry(QtCore.QRect(230, 260, 51, 25))
        self.label_lock_init_char_0.setStyleSheet("font-weight:bold")
        self.label_lock_init_char_0.setText("")
        self.label_lock_init_char_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_init_char_0.setObjectName("label_lock_init_char_0")
        self.label_lock_init_char_1 = QtWidgets.QLabel(self.tab)
        self.label_lock_init_char_1.setGeometry(QtCore.QRect(390, 260, 51, 25))
        self.label_lock_init_char_1.setStyleSheet("font-weight:bold")
        self.label_lock_init_char_1.setText("")
        self.label_lock_init_char_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_init_char_1.setObjectName("label_lock_init_char_1")
        self.label_lock_init_char_2 = QtWidgets.QLabel(self.tab)
        self.label_lock_init_char_2.setGeometry(QtCore.QRect(550, 260, 51, 25))
        self.label_lock_init_char_2.setStyleSheet("font-weight:bold")
        self.label_lock_init_char_2.setText("")
        self.label_lock_init_char_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_init_char_2.setObjectName("label_lock_init_char_2")
        self.label_lock_init_char_3 = QtWidgets.QLabel(self.tab)
        self.label_lock_init_char_3.setGeometry(QtCore.QRect(710, 260, 51, 25))
        self.label_lock_init_char_3.setStyleSheet("font-weight:bold")
        self.label_lock_init_char_3.setText("")
        self.label_lock_init_char_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_init_char_3.setObjectName("label_lock_init_char_3")
        self.checkBox_lock_init = QtWidgets.QCheckBox(self.tab)
        self.checkBox_lock_init.setGeometry(QtCore.QRect(0, 250, 101, 20))
        self.checkBox_lock_init.setObjectName("checkBox_lock_init")
        self.pushButton_init_open = QtWidgets.QPushButton(self.tab)
        self.pushButton_init_open.setGeometry(QtCore.QRect(0, 20, 93, 28))
        self.pushButton_init_open.setObjectName("pushButton_init_open")
        self.modifier_box = QtWidgets.QSpinBox(self.tab)
        self.modifier_box.setGeometry(QtCore.QRect(40, 140, 41, 22))
        self.modifier_box.setMinimum(-50)
        self.modifier_box.setObjectName("modifier_box")
        self.label_dice = QtWidgets.QLabel(self.tab)
        self.label_dice.setGeometry(QtCore.QRect(0, 120, 31, 16))
        self.label_dice.setObjectName("label_dice")
        self.label_modifier = QtWidgets.QLabel(self.tab)
        self.label_modifier.setGeometry(QtCore.QRect(0, 140, 31, 16))
        self.label_modifier.setObjectName("label_modifier")
        self.check_advantage = QtWidgets.QCheckBox(self.tab)
        self.check_advantage.setGeometry(QtCore.QRect(0, 160, 81, 20))
        self.check_advantage.setObjectName("check_advantage")
        self.comboBox_del_char = QtWidgets.QComboBox(self.tab)
        self.comboBox_del_char.setGeometry(QtCore.QRect(0, 210, 73, 22))
        self.comboBox_del_char.setObjectName("comboBox_del_char")
        self.pushButton_del_char = QtWidgets.QPushButton(self.tab)
        self.pushButton_del_char.setGeometry(QtCore.QRect(80, 210, 51, 22))
        self.pushButton_del_char.setObjectName("pushButton_del_char")
        self.label_del_char = QtWidgets.QLabel(self.tab)
        self.label_del_char.setGeometry(QtCore.QRect(0, 190, 101, 16))
        self.label_del_char.setObjectName("label_del_char")
        self.ac_character0 = QtWidgets.QLabel(self.tab)
        self.ac_character0.setGeometry(QtCore.QRect(210, 50, 25, 25))
        self.ac_character0.setStyleSheet("font-weight:bold")
        self.ac_character0.setObjectName("ac_character0")
        self.ac_edit_character0 = QtWidgets.QLineEdit(self.tab)
        self.ac_edit_character0.setGeometry(QtCore.QRect(240, 50, 31, 25))
        self.ac_edit_character0.setText("")
        self.ac_edit_character0.setObjectName("ac_edit_character0")
        self.ac_character1 = QtWidgets.QLabel(self.tab)
        self.ac_character1.setGeometry(QtCore.QRect(370, 50, 25, 25))
        self.ac_character1.setStyleSheet("font-weight:bold")
        self.ac_character1.setObjectName("ac_character1")
        self.ac_edit_character1 = QtWidgets.QLineEdit(self.tab)
        self.ac_edit_character1.setGeometry(QtCore.QRect(400, 50, 31, 25))
        self.ac_edit_character1.setText("")
        self.ac_edit_character1.setObjectName("ac_edit_character1")
        self.ac_character2 = QtWidgets.QLabel(self.tab)
        self.ac_character2.setGeometry(QtCore.QRect(540, 50, 25, 25))
        self.ac_character2.setStyleSheet("font-weight:bold")
        self.ac_character2.setObjectName("ac_character2")
        self.ac_edit_character2 = QtWidgets.QLineEdit(self.tab)
        self.ac_edit_character2.setGeometry(QtCore.QRect(570, 50, 31, 25))
        self.ac_edit_character2.setText("")
        self.ac_edit_character2.setObjectName("ac_edit_character2")
        self.ac_character3 = QtWidgets.QLabel(self.tab)
        self.ac_character3.setGeometry(QtCore.QRect(700, 50, 25, 25))
        self.ac_character3.setStyleSheet("font-weight:bold")
        self.ac_character3.setObjectName("ac_character3")
        self.ac_edit_character3 = QtWidgets.QLineEdit(self.tab)
        self.ac_edit_character3.setGeometry(QtCore.QRect(730, 50, 31, 25))
        self.ac_edit_character3.setText("")
        self.ac_edit_character3.setObjectName("ac_edit_character3")
        self.ac = QtWidgets.QLabel(self.tab)
        self.ac.setGeometry(QtCore.QRect(60, 80, 31, 25))
        self.ac.setStyleSheet("font-weight:bold")
        self.ac.setObjectName("ac")
        self.ac_edit = QtWidgets.QLineEdit(self.tab)
        self.ac_edit.setGeometry(QtCore.QRect(60, 105, 41, 25))
        self.ac_edit.setObjectName("ac_edit")
        self.checkBox_lock_ac = QtWidgets.QCheckBox(self.tab)
        self.checkBox_lock_ac.setGeometry(QtCore.QRect(0, 280, 121, 20))
        self.checkBox_lock_ac.setObjectName("checkBox_lock_ac")
        self.label_lock_ac_char_0 = QtWidgets.QLabel(self.tab)
        self.label_lock_ac_char_0.setGeometry(QtCore.QRect(240, 50, 31, 25))
        self.label_lock_ac_char_0.setStyleSheet("font-weight:bold")
        self.label_lock_ac_char_0.setText("")
        self.label_lock_ac_char_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_ac_char_0.setObjectName("label_lock_ac_char_0")
        self.label_lock_ac_char_1 = QtWidgets.QLabel(self.tab)
        self.label_lock_ac_char_1.setGeometry(QtCore.QRect(400, 50, 31, 25))
        self.label_lock_ac_char_1.setStyleSheet("font-weight:bold")
        self.label_lock_ac_char_1.setText("")
        self.label_lock_ac_char_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_ac_char_1.setObjectName("label_lock_ac_char_1")
        self.label_lock_ac_char_2 = QtWidgets.QLabel(self.tab)
        self.label_lock_ac_char_2.setGeometry(QtCore.QRect(570, 50, 31, 25))
        self.label_lock_ac_char_2.setStyleSheet("font-weight:bold")
        self.label_lock_ac_char_2.setText("")
        self.label_lock_ac_char_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_ac_char_2.setObjectName("label_lock_ac_char_2")
        self.label_lock_ac_char_3 = QtWidgets.QLabel(self.tab)
        self.label_lock_ac_char_3.setGeometry(QtCore.QRect(730, 50, 31, 25))
        self.label_lock_ac_char_3.setStyleSheet("font-weight:bold")
        self.label_lock_ac_char_3.setText("")
        self.label_lock_ac_char_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lock_ac_char_3.setObjectName("label_lock_ac_char_3")
        self.textEdit_char_0 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_char_0.setGeometry(QtCore.QRect(160, 290, 120, 70))
        self.textEdit_char_0.setObjectName("textEdit_char_0")
        self.textEdit_char_1 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_char_1.setGeometry(QtCore.QRect(320, 290, 120, 70))
        self.textEdit_char_1.setObjectName("textEdit_char_1")
        self.textEdit_char_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_char_2.setGeometry(QtCore.QRect(480, 290, 120, 70))
        self.textEdit_char_2.setObjectName("textEdit_char_2")
        self.textEdit_char_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_char_3.setGeometry(QtCore.QRect(640, 290, 120, 70))
        self.textEdit_char_3.setObjectName("textEdit_char_3")
        self.pushButton_set_spell_slots_0 = QtWidgets.QPushButton(self.tab)
        self.pushButton_set_spell_slots_0.setGeometry(QtCore.QRect(260, 230, 31, 28))
        self.pushButton_set_spell_slots_0.setObjectName("pushButton_set_spell_slots_0")
        self.pushButton_set_spell_slots_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_set_spell_slots_1.setGeometry(QtCore.QRect(420, 230, 31, 28))
        self.pushButton_set_spell_slots_1.setObjectName("pushButton_set_spell_slots_1")
        self.pushButton_set_spell_slots_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_set_spell_slots_2.setGeometry(QtCore.QRect(590, 230, 31, 28))
        self.pushButton_set_spell_slots_2.setObjectName("pushButton_set_spell_slots_2")
        self.pushButton_set_spell_slots_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_set_spell_slots_3.setGeometry(QtCore.QRect(750, 230, 31, 28))
        self.pushButton_set_spell_slots_3.setObjectName("pushButton_set_spell_slots_3")
        self.checkBox_hide_spell_slot_char_0 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hide_spell_slot_char_0.setGeometry(QtCore.QRect(220, 80, 61, 25))
        self.checkBox_hide_spell_slot_char_0.setStyleSheet("font-weight:bold")
        self.checkBox_hide_spell_slot_char_0.setObjectName("checkBox_hide_spell_slot_char_0")
        self.checkBox_hide_spell_slot_char_1 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hide_spell_slot_char_1.setGeometry(QtCore.QRect(380, 80, 61, 25))
        self.checkBox_hide_spell_slot_char_1.setStyleSheet("font-weight:bold")
        self.checkBox_hide_spell_slot_char_1.setObjectName("checkBox_hide_spell_slot_char_1")
        self.checkBox_hide_spell_slot_char_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hide_spell_slot_char_2.setGeometry(QtCore.QRect(550, 80, 61, 25))
        self.checkBox_hide_spell_slot_char_2.setStyleSheet("font-weight:bold")
        self.checkBox_hide_spell_slot_char_2.setObjectName("checkBox_hide_spell_slot_char_2")
        self.checkBox_hide_spell_slot_char_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_hide_spell_slot_char_3.setGeometry(QtCore.QRect(710, 80, 61, 25))
        self.checkBox_hide_spell_slot_char_3.setStyleSheet("font-weight:bold")
        self.checkBox_hide_spell_slot_char_3.setObjectName("checkBox_hide_spell_slot_char_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.text_scenario = QtWidgets.QTextEdit(self.tab_7)
        self.text_scenario.setGeometry(QtCore.QRect(233, 6, 551, 361))
        self.text_scenario.setObjectName("text_scenario")
        self.list_tags = QtWidgets.QListWidget(self.tab_7)
        self.list_tags.setGeometry(QtCore.QRect(10, 40, 201, 301))
        self.list_tags.setObjectName("list_tags")
        self.pushButton_add_tags = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_add_tags.setGeometry(QtCore.QRect(10, 10, 51, 28))
        self.pushButton_add_tags.setObjectName("pushButton_add_tags")
        self.pushButton_del_tags = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_del_tags.setGeometry(QtCore.QRect(160, 10, 51, 28))
        self.pushButton_del_tags.setObjectName("pushButton_del_tags")
        self.radioButton_tags_notes = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_tags_notes.setGeometry(QtCore.QRect(10, 350, 95, 20))
        self.radioButton_tags_notes.setObjectName("radioButton_tags_notes")
        self.pushButton_add_chapter = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_add_chapter.setGeometry(QtCore.QRect(240, 10, 41, 28))
        self.pushButton_add_chapter.setObjectName("pushButton_add_chapter")
        self.edit_add_chapter = QtWidgets.QLineEdit(self.tab_7)
        self.edit_add_chapter.setGeometry(QtCore.QRect(10, 10, 231, 28))
        self.edit_add_chapter.setObjectName("edit_add_chapter")
        self.comboBox_choose_chapter = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_choose_chapter.setGeometry(QtCore.QRect(330, 10, 451, 28))
        self.comboBox_choose_chapter.setObjectName("comboBox_choose_chapter")
        self.text_chapter = QtWidgets.QTextEdit(self.tab_7)
        self.text_chapter.setGeometry(QtCore.QRect(10, 40, 771, 311))
        self.text_chapter.setObjectName("text_chapter")
        self.pushButton_del_chapter = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_del_chapter.setGeometry(QtCore.QRect(290, 10, 41, 28))
        self.pushButton_del_chapter.setObjectName("pushButton_del_chapter")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.note_edit_0 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.note_edit_0.setObjectName("note_edit_0")
        self.horizontalLayout.addWidget(self.note_edit_0)
        self.note_edit_1 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.note_edit_1.setObjectName("note_edit_1")
        self.horizontalLayout.addWidget(self.note_edit_1)
        self.note_edit_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.note_edit_2.setObjectName("note_edit_2")
        self.horizontalLayout.addWidget(self.note_edit_2)
        self.note_edit_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.note_edit_3.setObjectName("note_edit_3")
        self.horizontalLayout.addWidget(self.note_edit_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scene_edit = QtWidgets.QLineEdit(self.tab_2)
        self.scene_edit.setGeometry(QtCore.QRect(110, 40, 113, 22))
        self.scene_edit.setObjectName("scene_edit")
        self.url_edit = QtWidgets.QLineEdit(self.tab_2)
        self.url_edit.setGeometry(QtCore.QRect(230, 40, 361, 22))
        self.url_edit.setObjectName("url_edit")
        self.pushButton_url_set = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_url_set.setGeometry(QtCore.QRect(610, 35, 93, 28))
        self.pushButton_url_set.setObjectName("pushButton_url_set")
        self.pushButton_url_open = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_url_open.setGeometry(QtCore.QRect(340, 85, 93, 28))
        self.pushButton_url_open.setObjectName("pushButton_url_open")
        self.pushButton_url_delete = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_url_delete.setGeometry(QtCore.QRect(340, 330, 93, 28))
        self.pushButton_url_delete.setObjectName("pushButton_url_delete")
        self.label_scene = QtWidgets.QLabel(self.tab_2)
        self.label_scene.setGeometry(QtCore.QRect(110, 20, 111, 16))
        self.label_scene.setStyleSheet("font-weight:bold")
        self.label_scene.setObjectName("label_scene")
        self.label_scene_url = QtWidgets.QLabel(self.tab_2)
        self.label_scene_url.setGeometry(QtCore.QRect(230, 20, 111, 16))
        self.label_scene_url.setStyleSheet("font-weight:bold")
        self.label_scene_url.setObjectName("label_scene_url")
        self.label_scene_url_2 = QtWidgets.QLabel(self.tab_2)
        self.label_scene_url_2.setGeometry(QtCore.QRect(180, 70, 111, 16))
        self.label_scene_url_2.setStyleSheet("font-weight:bold")
        self.label_scene_url_2.setObjectName("label_scene_url_2")
        self.label_category = QtWidgets.QLabel(self.tab_2)
        self.label_category.setGeometry(QtCore.QRect(0, 20, 111, 16))
        self.label_category.setStyleSheet("font-weight:bold")
        self.label_category.setObjectName("label_category")
        self.category_edit = QtWidgets.QLineEdit(self.tab_2)
        self.category_edit.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.category_edit.setObjectName("category_edit")
        self.label_category_open = QtWidgets.QLabel(self.tab_2)
        self.label_category_open.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_category_open.setStyleSheet("font-weight:bold")
        self.label_category_open.setObjectName("label_category_open")
        self.listWidget_category = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_category.setGeometry(QtCore.QRect(10, 90, 151, 271))
        self.listWidget_category.setObjectName("listWidget_category")
        self.listWidget_scene = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_scene.setGeometry(QtCore.QRect(180, 90, 151, 271))
        self.listWidget_scene.setObjectName("listWidget_scene")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox_rules = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_rules.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.comboBox_rules.setObjectName("comboBox_rules")
        self.label_rules = QtWidgets.QTextEdit(self.tab_3)
        self.label_rules.setGeometry(QtCore.QRect(10, 30, 771, 331))
        self.label_rules.setReadOnly(True)
        self.label_rules.setObjectName("label_rules")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.box_choose_shop = QtWidgets.QComboBox(self.tab_5)
        self.box_choose_shop.setGeometry(QtCore.QRect(10, 10, 161, 22))
        self.box_choose_shop.setObjectName("box_choose_shop")
        self.text_notes = QtWidgets.QTextEdit(self.tab_5)
        self.text_notes.setGeometry(QtCore.QRect(10, 60, 200, 300))
        self.text_notes.setObjectName("text_notes")
        self.label_shop_info = QtWidgets.QLabel(self.tab_5)
        self.label_shop_info.setGeometry(QtCore.QRect(279, 60, 241, 300))
        self.label_shop_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_shop_info.setObjectName("label_shop_info")
        self.text_assortment_shop = QtWidgets.QTextEdit(self.tab_5)
        self.text_assortment_shop.setGeometry(QtCore.QRect(580, 60, 200, 301))
        self.text_assortment_shop.setObjectName("text_assortment_shop")
        self.search_assortment_edit = QtWidgets.QLineEdit(self.tab_5)
        self.search_assortment_edit.setGeometry(QtCore.QRect(580, 30, 201, 22))
        self.search_assortment_edit.setObjectName("search_assortment_edit")
        self.pushButton_generate_shop = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_generate_shop.setGeometry(QtCore.QRect(480, 30, 93, 28))
        self.pushButton_generate_shop.setObjectName("pushButton_generate_shop")
        self.box_generate_type = QtWidgets.QComboBox(self.tab_5)
        self.box_generate_type.setGeometry(QtCore.QRect(312, 30, 161, 28))
        self.box_generate_type.setObjectName("box_generate_type")
        self.pushButton_del_store = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_del_store.setGeometry(QtCore.QRect(170, 10, 41, 22))
        self.pushButton_del_store.setObjectName("pushButton_del_store")
        self.box_generate_cost = QtWidgets.QComboBox(self.tab_5)
        self.box_generate_cost.setGeometry(QtCore.QRect(220, 30, 81, 28))
        self.box_generate_cost.setObjectName("box_generate_cost")
        self.label_cost_generate = QtWidgets.QLabel(self.tab_5)
        self.label_cost_generate.setGeometry(QtCore.QRect(220, 10, 31, 16))
        self.label_cost_generate.setObjectName("label_cost_generate")
        self.label_type_generate = QtWidgets.QLabel(self.tab_5)
        self.label_type_generate.setGeometry(QtCore.QRect(310, 10, 55, 16))
        self.label_type_generate.setObjectName("label_type_generate")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(580, 10, 131, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton_options_store = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_options_store.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.radioButton_options_store.setObjectName("radioButton_options_store")
        self.label_sex_vendor = QtWidgets.QLabel(self.tab_5)
        self.label_sex_vendor.setGeometry(QtCore.QRect(10, 200, 55, 16))
        self.label_sex_vendor.setObjectName("label_sex_vendor")
        self.edit_name_vendor = QtWidgets.QLineEdit(self.tab_5)
        self.edit_name_vendor.setGeometry(QtCore.QRect(10, 160, 161, 22))
        self.edit_name_vendor.setObjectName("edit_name_vendor")
        self.box_sex_vendor = QtWidgets.QComboBox(self.tab_5)
        self.box_sex_vendor.setGeometry(QtCore.QRect(10, 220, 161, 22))
        self.box_sex_vendor.setObjectName("box_sex_vendor")
        self.label_age_vendor = QtWidgets.QLabel(self.tab_5)
        self.label_age_vendor.setGeometry(QtCore.QRect(10, 260, 55, 16))
        self.label_age_vendor.setObjectName("label_age_vendor")
        self.box_age_vendor = QtWidgets.QComboBox(self.tab_5)
        self.box_age_vendor.setGeometry(QtCore.QRect(10, 280, 161, 22))
        self.box_age_vendor.setObjectName("box_age_vendor")
        self.box_race_vendor = QtWidgets.QComboBox(self.tab_5)
        self.box_race_vendor.setGeometry(QtCore.QRect(10, 340, 161, 22))
        self.box_race_vendor.setObjectName("box_race_vendor")
        self.label_race_vendor = QtWidgets.QLabel(self.tab_5)
        self.label_race_vendor.setGeometry(QtCore.QRect(10, 320, 55, 16))
        self.label_race_vendor.setObjectName("label_race_vendor")
        self.label_name_vendor = QtWidgets.QLabel(self.tab_5)
        self.label_name_vendor.setGeometry(QtCore.QRect(10, 140, 55, 16))
        self.label_name_vendor.setObjectName("label_name_vendor")
        self.label_store_name_2 = QtWidgets.QLabel(self.tab_5)
        self.label_store_name_2.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_store_name_2.setObjectName("label_store_name_2")
        self.edit_store_name_2 = QtWidgets.QLineEdit(self.tab_5)
        self.edit_store_name_2.setGeometry(QtCore.QRect(10, 80, 161, 22))
        self.edit_store_name_2.setObjectName("edit_store_name_2")
        self.label_vendor = QtWidgets.QLabel(self.tab_5)
        self.label_vendor.setGeometry(QtCore.QRect(10, 120, 55, 16))
        self.label_vendor.setStyleSheet("font-weight:bold")
        self.label_vendor.setObjectName("label_vendor")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_generate_npc = QtWidgets.QLabel(self.tab_6)
        self.label_generate_npc.setGeometry(QtCore.QRect(205, 64, 170, 291))
        self.label_generate_npc.setStyleSheet("font-weight:bold")
        self.label_generate_npc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_generate_npc.setObjectName("label_generate_npc")
        self.text_npc_generate = QtWidgets.QTextEdit(self.tab_6)
        self.text_npc_generate.setGeometry(QtCore.QRect(410, 19, 371, 340))
        self.text_npc_generate.setObjectName("text_npc_generate")
        self.pushButton_generate_npc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_generate_npc.setGeometry(QtCore.QRect(20, 290, 93, 28))
        self.pushButton_generate_npc.setObjectName("pushButton_generate_npc")
        self.box_generate_npc = QtWidgets.QComboBox(self.tab_6)
        self.box_generate_npc.setGeometry(QtCore.QRect(205, 10, 170, 22))
        self.box_generate_npc.setObjectName("box_generate_npc")
        self.pushButton_del_npc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_del_npc.setGeometry(QtCore.QRect(40, 340, 51, 22))
        self.pushButton_del_npc.setObjectName("pushButton_del_npc")
        self.edit_npc_name = QtWidgets.QLineEdit(self.tab_6)
        self.edit_npc_name.setGeometry(QtCore.QRect(10, 60, 161, 22))
        self.edit_npc_name.setObjectName("edit_npc_name")
        self.label_npc_name = QtWidgets.QLabel(self.tab_6)
        self.label_npc_name.setGeometry(QtCore.QRect(10, 40, 55, 16))
        self.label_npc_name.setObjectName("label_npc_name")
        self.box_sex_npc = QtWidgets.QComboBox(self.tab_6)
        self.box_sex_npc.setGeometry(QtCore.QRect(10, 120, 161, 22))
        self.box_sex_npc.setObjectName("box_sex_npc")
        self.label_sex_npc = QtWidgets.QLabel(self.tab_6)
        self.label_sex_npc.setGeometry(QtCore.QRect(10, 100, 55, 16))
        self.label_sex_npc.setObjectName("label_sex_npc")
        self.label_age_npc = QtWidgets.QLabel(self.tab_6)
        self.label_age_npc.setGeometry(QtCore.QRect(10, 160, 55, 16))
        self.label_age_npc.setObjectName("label_age_npc")
        self.box_age_npc = QtWidgets.QComboBox(self.tab_6)
        self.box_age_npc.setGeometry(QtCore.QRect(10, 180, 161, 22))
        self.box_age_npc.setObjectName("box_age_npc")
        self.label_race_npc = QtWidgets.QLabel(self.tab_6)
        self.label_race_npc.setGeometry(QtCore.QRect(10, 220, 55, 16))
        self.label_race_npc.setObjectName("label_race_npc")
        self.box_race_npc = QtWidgets.QComboBox(self.tab_6)
        self.box_race_npc.setGeometry(QtCore.QRect(10, 240, 161, 22))
        self.box_race_npc.setObjectName("box_race_npc")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionlast_session = QtGui.QAction(MainWindow)
        self.actionlast_session.setObjectName("actionlast_session")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionlast_session)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DnD Master support"))
        self.hp.setText(_translate("MainWindow", "Hp"))
        self.pushButton.setText(_translate("MainWindow", "Create"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.initiative.setText(_translate("MainWindow", "Initiative"))
        self.pushButton_roll_dice.setText(_translate("MainWindow", "Roll dice"))
        self.dice_edit.setText(_translate("MainWindow", "20"))
        self.label_amount.setText(_translate("MainWindow", "Amout"))
        self.radioButton_hide_create.setText(_translate("MainWindow", "Creation off"))
        self.name_character0.setText(_translate("MainWindow", "Name"))
        self.hp_character0.setText(_translate("MainWindow", "Hp"))
        self.initiative_character0.setText(_translate("MainWindow", "Initiative"))
        self.name_character1.setText(_translate("MainWindow", "Name"))
        self.initiative_character1.setText(_translate("MainWindow", "Initiative"))
        self.hp_character1.setText(_translate("MainWindow", "Hp"))
        self.name_character2.setText(_translate("MainWindow", "Name"))
        self.initiative_character3.setText(_translate("MainWindow", "Initiative"))
        self.name_character3.setText(_translate("MainWindow", "Name"))
        self.initiative_character2.setText(_translate("MainWindow", "Initiative"))
        self.hp_character3.setText(_translate("MainWindow", "Hp"))
        self.hp_character2.setText(_translate("MainWindow", "Hp"))
        self.spell_slot_edit.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_2.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_3.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_4.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_5.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_6.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_7.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_8.setText(_translate("MainWindow", "0"))
        self.spell_slot_edit_9.setText(_translate("MainWindow", "0"))
        self.spell_slot.setText(_translate("MainWindow", "Spell slot"))
        self.label_spell_slot.setText(_translate("MainWindow", "1"))
        self.label_spell_slot_2.setText(_translate("MainWindow", "2"))
        self.label_spell_slot_3.setText(_translate("MainWindow", "3"))
        self.label_spell_slot_4.setText(_translate("MainWindow", "4"))
        self.label_spell_slot_5.setText(_translate("MainWindow", "5"))
        self.label_spell_slot_6.setText(_translate("MainWindow", "6"))
        self.label_spell_slot_7.setText(_translate("MainWindow", "7"))
        self.label_spell_slot_8.setText(_translate("MainWindow", "8"))
        self.label_spell_slot_9.setText(_translate("MainWindow", "9"))
        self.label_spell_slot_character0.setText(_translate("MainWindow", "1"))
        self.label_spell_slot_character0_2.setText(_translate("MainWindow", "2"))
        self.label_spell_slot_character0_3.setText(_translate("MainWindow", "3"))
        self.label_spell_slot_character0_4.setText(_translate("MainWindow", "4"))
        self.label_spell_slot_character0_5.setText(_translate("MainWindow", "5"))
        self.label_spell_slot_character0_6.setText(_translate("MainWindow", "6"))
        self.label_spell_slot_character0_7.setText(_translate("MainWindow", "7"))
        self.label_spell_slot_character0_8.setText(_translate("MainWindow", "8"))
        self.label_spell_slot_character0_9.setText(_translate("MainWindow", "9"))
        self.spell_slot_label_traker_char0.setText(_translate("MainWindow", "Spell slot"))
        self.label_spell_slot_character0_10.setText(_translate("MainWindow", "9"))
        self.spell_slot_label_traker_char1.setText(_translate("MainWindow", "Spell slot"))
        self.label_spell_slot_character0_11.setText(_translate("MainWindow", "8"))
        self.label_spell_slot_character0_12.setText(_translate("MainWindow", "7"))
        self.label_spell_slot_character0_13.setText(_translate("MainWindow", "2"))
        self.label_spell_slot_character0_14.setText(_translate("MainWindow", "4"))
        self.label_spell_slot_character0_15.setText(_translate("MainWindow", "1"))
        self.label_spell_slot_character0_16.setText(_translate("MainWindow", "5"))
        self.label_spell_slot_character0_17.setText(_translate("MainWindow", "3"))
        self.label_spell_slot_character0_18.setText(_translate("MainWindow", "6"))
        self.label_spell_slot_character0_19.setText(_translate("MainWindow", "4"))
        self.label_spell_slot_character0_20.setText(_translate("MainWindow", "7"))
        self.label_spell_slot_character0_21.setText(_translate("MainWindow", "2"))
        self.spell_slot_label_traker_char2.setText(_translate("MainWindow", "Spell slot"))
        self.label_spell_slot_character0_22.setText(_translate("MainWindow", "8"))
        self.label_spell_slot_character0_23.setText(_translate("MainWindow", "6"))
        self.label_spell_slot_character0_24.setText(_translate("MainWindow", "1"))
        self.label_spell_slot_character0_25.setText(_translate("MainWindow", "5"))
        self.label_spell_slot_character0_26.setText(_translate("MainWindow", "3"))
        self.label_spell_slot_character0_27.setText(_translate("MainWindow", "9"))
        self.label_spell_slot_character0_28.setText(_translate("MainWindow", "4"))
        self.label_spell_slot_character0_29.setText(_translate("MainWindow", "7"))
        self.label_spell_slot_character0_30.setText(_translate("MainWindow", "2"))
        self.spell_slot_label_traker_char3.setText(_translate("MainWindow", "Spell slot"))
        self.label_spell_slot_character0_31.setText(_translate("MainWindow", "8"))
        self.label_spell_slot_character0_32.setText(_translate("MainWindow", "6"))
        self.label_spell_slot_character0_33.setText(_translate("MainWindow", "1"))
        self.label_spell_slot_character0_34.setText(_translate("MainWindow", "5"))
        self.label_spell_slot_character0_35.setText(_translate("MainWindow", "3"))
        self.label_spell_slot_character0_36.setText(_translate("MainWindow", "9"))
        self.pushButton_restore_spell_slots_0.setText(_translate("MainWindow", "Restore slot"))
        self.pushButton_restore_spell_slots_1.setText(_translate("MainWindow", "Restore slot"))
        self.pushButton_restore_spell_slots_2.setText(_translate("MainWindow", "Restore slot"))
        self.pushButton_restore_spell_slots_3.setText(_translate("MainWindow", "Restore slot"))
        self.checkBox_lock_init.setText(_translate("MainWindow", "lock initiative"))
        self.pushButton_init_open.setText(_translate("MainWindow", "Initiative"))
        self.label_dice.setText(_translate("MainWindow", "Dice"))
        self.label_modifier.setText(_translate("MainWindow", "Mod"))
        self.check_advantage.setText(_translate("MainWindow", "advantage"))
        self.pushButton_del_char.setText(_translate("MainWindow", "Delete"))
        self.label_del_char.setText(_translate("MainWindow", "Delete character"))
        self.ac_character0.setText(_translate("MainWindow", "Ac"))
        self.ac_character1.setText(_translate("MainWindow", "Ac"))
        self.ac_character2.setText(_translate("MainWindow", "Ac"))
        self.ac_character3.setText(_translate("MainWindow", "Ac"))
        self.ac.setText(_translate("MainWindow", "Ac"))
        self.checkBox_lock_ac.setText(_translate("MainWindow", "lock armor class"))
        self.pushButton_set_spell_slots_0.setText(_translate("MainWindow", "set"))
        self.pushButton_set_spell_slots_1.setText(_translate("MainWindow", "set"))
        self.pushButton_set_spell_slots_2.setText(_translate("MainWindow", "set"))
        self.pushButton_set_spell_slots_3.setText(_translate("MainWindow", "set"))
        self.checkBox_hide_spell_slot_char_0.setText(_translate("MainWindow", "hide"))
        self.checkBox_hide_spell_slot_char_1.setText(_translate("MainWindow", "hide"))
        self.checkBox_hide_spell_slot_char_2.setText(_translate("MainWindow", "hide"))
        self.checkBox_hide_spell_slot_char_3.setText(_translate("MainWindow", "hide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tracker"))
        self.pushButton_add_tags.setText(_translate("MainWindow", "Add"))
        self.pushButton_del_tags.setText(_translate("MainWindow", "delete"))
        self.radioButton_tags_notes.setText(_translate("MainWindow", "tags notes"))
        self.pushButton_add_chapter.setText(_translate("MainWindow", "add"))
        self.pushButton_del_chapter.setText(_translate("MainWindow", "del"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Scenario"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Notes"))
        self.pushButton_url_set.setText(_translate("MainWindow", "set"))
        self.pushButton_url_open.setText(_translate("MainWindow", "open"))
        self.pushButton_url_delete.setText(_translate("MainWindow", "delete"))
        self.label_scene.setText(_translate("MainWindow", "Scene name"))
        self.label_scene_url.setText(_translate("MainWindow", "URL music"))
        self.label_scene_url_2.setText(_translate("MainWindow", "Choose scene"))
        self.label_category.setText(_translate("MainWindow", "Category name"))
        self.label_category_open.setText(_translate("MainWindow", "Category name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Music changer"))
        self.label_rules.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Rules"))
        self.label_shop_info.setText(_translate("MainWindow", "Shop_info"))
        self.pushButton_generate_shop.setText(_translate("MainWindow", "Generate"))
        self.pushButton_del_store.setText(_translate("MainWindow", "del"))
        self.label_cost_generate.setText(_translate("MainWindow", "Cost"))
        self.label_type_generate.setText(_translate("MainWindow", "Type"))
        self.label_2.setText(_translate("MainWindow", "Search by assortment"))
        self.radioButton_options_store.setText(_translate("MainWindow", "options"))
        self.label_sex_vendor.setText(_translate("MainWindow", "Sex"))
        self.label_age_vendor.setText(_translate("MainWindow", "Age"))
        self.label_race_vendor.setText(_translate("MainWindow", "Race"))
        self.label_name_vendor.setText(_translate("MainWindow", "Name"))
        self.label_store_name_2.setText(_translate("MainWindow", "Name store"))
        self.label_vendor.setText(_translate("MainWindow", "Vendor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Generate store"))
        self.label_generate_npc.setText(_translate("MainWindow", "Text NPC"))
        self.pushButton_generate_npc.setText(_translate("MainWindow", "Generate"))
        self.pushButton_del_npc.setText(_translate("MainWindow", "Delete"))
        self.label_npc_name.setText(_translate("MainWindow", "Name"))
        self.label_sex_npc.setText(_translate("MainWindow", "Sex"))
        self.label_age_npc.setText(_translate("MainWindow", "Age"))
        self.label_race_npc.setText(_translate("MainWindow", "Race"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "NPC generator"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionlast_session.setText(_translate("MainWindow", "last session"))

        self.hide_aplications()


    def hide_aplications(self):
        self.pushButton_init_open.hide()
        self.dice_edit.hide()
        self.amount_dice_box.hide()
        self.modifier_box.hide()
        self.label_amount.hide()
        self.label_dice.hide()
        self.label_modifier.hide()
        self.label_roll_dice.hide()
        self.check_advantage.hide()
        self.pushButton_roll_dice.hide()
        self.label_del_char.hide()
        self.comboBox_del_char.hide()
        self.pushButton_del_char.hide()
        self.name_character0.hide()
        self.name_character1.hide()
        self.name_character2.hide()
        self.name_character3.hide()
        self.hp_character0.hide()
        self.hp_character1.hide()
        self.hp_character2.hide()
        self.hp_character3.hide()
        self.hp_edit_character0.hide()
        self.hp_edit_character1.hide()
        self.hp_edit_character2.hide()
        self.hp_edit_character3.hide()
        self.ac_character0.hide()
        self.ac_character1.hide()
        self.ac_character2.hide()
        self.ac_character3.hide()
        self.ac_edit_character0.hide()
        self.ac_edit_character1.hide()
        self.ac_edit_character2.hide()
        self.ac_edit_character3.hide()
        self.initiative_character0.hide()
        self.initiative_character1.hide()
        self.initiative_character2.hide()
        self.initiative_character3.hide()
        self.initiative_edit_character0.hide()
        self.initiative_edit_character1.hide()
        self.initiative_edit_character2.hide()
        self.initiative_edit_character3.hide()
        self.checkBox_hide_spell_slot_char_0.hide()
        self.checkBox_hide_spell_slot_char_1.hide()
        self.checkBox_hide_spell_slot_char_2.hide()
        self.checkBox_hide_spell_slot_char_3.hide()
        self.label_spell_slot_character0.hide()
        self.label_spell_slot_character0_2.hide()
        self.label_spell_slot_character0_3.hide()
        self.label_spell_slot_character0_4.hide()
        self.label_spell_slot_character0_5.hide()
        self.label_spell_slot_character0_6.hide()
        self.label_spell_slot_character0_7.hide()
        self.label_spell_slot_character0_8.hide()
        self.label_spell_slot_character0_9.hide()
        self.spell_slot_label_traker_char0.hide()
        self.label_spell_slot_character0_10.hide()
        self.spell_slot_label_traker_char1.hide()
        self.label_spell_slot_character0_11.hide()
        self.label_spell_slot_character0_12.hide()
        self.label_spell_slot_character0_13.hide()
        self.label_spell_slot_character0_14.hide()
        self.label_spell_slot_character0_15.hide()
        self.label_spell_slot_character0_16.hide()
        self.label_spell_slot_character0_17.hide()
        self.label_spell_slot_character0_18.hide()
        self.label_spell_slot_character0_19.hide()
        self.label_spell_slot_character0_20.hide()
        self.label_spell_slot_character0_21.hide()
        self.spell_slot_label_traker_char2.hide()
        self.label_spell_slot_character0_22.hide()
        self.label_spell_slot_character0_23.hide()
        self.label_spell_slot_character0_24.hide()
        self.label_spell_slot_character0_25.hide()
        self.label_spell_slot_character0_26.hide()
        self.label_spell_slot_character0_27.hide()
        self.label_spell_slot_character0_28.hide()
        self.label_spell_slot_character0_29.hide()
        self.label_spell_slot_character0_30.hide()
        self.spell_slot_label_traker_char3.hide()
        self.label_spell_slot_character0_31.hide()
        self.label_spell_slot_character0_32.hide()
        self.label_spell_slot_character0_33.hide()
        self.label_spell_slot_character0_34.hide()
        self.label_spell_slot_character0_35.hide()
        self.label_spell_slot_character0_36.hide()
        self.spin_spell_slot_character0.hide()
        self.spin_spell_slot_character0_2.hide()
        self.spin_spell_slot_character0_3.hide()
        self.spin_spell_slot_character0_4.hide()
        self.spin_spell_slot_character0_5.hide()
        self.spin_spell_slot_character0_6.hide()
        self.spin_spell_slot_character0_7.hide()
        self.spin_spell_slot_character0_8.hide()
        self.spin_spell_slot_character0_9.hide()
        self.spin_spell_slot_character1.hide()
        self.spin_spell_slot_character1_2.hide()
        self.spin_spell_slot_character1_3.hide()
        self.spin_spell_slot_character1_4.hide()
        self.spin_spell_slot_character1_5.hide()
        self.spin_spell_slot_character1_6.hide()
        self.spin_spell_slot_character1_7.hide()
        self.spin_spell_slot_character1_8.hide()
        self.spin_spell_slot_character1_9.hide()
        self.spin_spell_slot_character2.hide()
        self.spin_spell_slot_character2_2.hide()
        self.spin_spell_slot_character2_3.hide()
        self.spin_spell_slot_character2_4.hide()
        self.spin_spell_slot_character2_5.hide()
        self.spin_spell_slot_character2_6.hide()
        self.spin_spell_slot_character2_7.hide()
        self.spin_spell_slot_character2_8.hide()
        self.spin_spell_slot_character2_9.hide()
        self.spin_spell_slot_character3.hide()
        self.spin_spell_slot_character3_2.hide()
        self.spin_spell_slot_character3_3.hide()
        self.spin_spell_slot_character3_4.hide()
        self.spin_spell_slot_character3_5.hide()
        self.spin_spell_slot_character3_6.hide()
        self.spin_spell_slot_character3_7.hide()
        self.spin_spell_slot_character3_8.hide()
        self.spin_spell_slot_character3_9.hide()
        self.pushButton_restore_spell_slots_0.hide()
        self.pushButton_restore_spell_slots_1.hide()
        self.pushButton_restore_spell_slots_2.hide()
        self.pushButton_restore_spell_slots_3.hide()
        self.pushButton_set_spell_slots_0.hide()
        self.pushButton_set_spell_slots_1.hide()
        self.pushButton_set_spell_slots_2.hide()
        self.pushButton_set_spell_slots_3.hide()
        self.checkBox_lock_init.hide()
        self.checkBox_lock_ac.hide()
        self.textEdit_char_0.hide()
        self.textEdit_char_1.hide()
        self.textEdit_char_2.hide()
        self.textEdit_char_3.hide()
        self.label_store_name_2.hide()
        self.edit_store_name_2.hide()
        self.label_vendor.hide()
        self.label_name_vendor.hide()
        self.edit_name_vendor.hide()
        self.label_sex_vendor.hide()
        self.box_sex_vendor.hide()
        self.label_age_vendor.hide()
        self.box_age_vendor.hide()
        self.label_race_vendor.hide()
        self.box_race_vendor.hide()
        self.pushButton_add_tags.hide()
        self.pushButton_del_tags.hide()
        self.list_tags.hide()
        self.text_scenario.hide()

        self.name.show()
        self.name_edit.show()
        self.hp.show()
        self.hp_edit.show()
        self.initiative.show()
        self.initiative_edit.show()
        self.pushButton.show()
        self.label.show()
